### ISSUE TITLE
Example of `Try` in documentation implies that `Try` tests the error when it actually just returns the error

### ISSUE THREAD

**Issue by puiutucutu** [ericelliott/riteway#106]
# Comment

When looking at the provided example showing how to use the `Try` function, it gave me the impression that somewhere down the line, the `assert` function will use the `expected` property to match the supplied error both against the error prototype and the message when this is not actually the case.

The example is taken from <https://github.com/ericelliott/riteway#example-usage> .

```js
// a function to test
const sum = (...args) => {
  if (args.some(v => Number.isNaN(v))) throw new TypeError('NaN');
  return args.reduce((acc, n) => acc + n, 0);
};

[...]

assert({
  given: 'NaN',
  should: 'throw',
  actual: Try(sum, 1, NaN),
  expected: new TypeError('NaN') // in question
});
```

In fact, the `Try` fn is a safety wrapper for handling errors arising in promises and does not perform any equality checks.

```js
const Try = (fn = noop, ...args) => {
  try {
    return catchPromise(fn(...args));
  } catch (err) {
    return err;
  }
};
```

Additionally, one can even use `Try` in any of the following ways and the tests will all still pass. This is due to the behaviour of `deepEqual()` from `tape` which itself uses the `deep-equal` project from <https://github.com/substack/node-deep-equal>. Maybe this is the intended behavior but I got confused.

```js
assert({
  given: 'NaN',
  should: 'throw',
  actual: Try(sum, 1, NaN),
  expected: new TypeError()
});

assert({
  given: 'NaN',
  should: 'throw',
  actual: Try(sum, 1, NaN),
  expected: new TypeError
});

assert({
  given: 'NaN',
  should: 'throw',
  actual: Try(sum, 1, NaN),
  expected: new TypeError("Has a different error message")
});
```

# Suggestion

## 1 - Change the error message for the TypeError 

The `NaN` string is confusing with the `given: 'NaN'` used in the `assert` as well, so just change the error message thrown to make this clearer.

```js
// a function to test
const sum = (...args) => {
  if (args.some(v => Number.isNaN(v))) throw new TypeError('Not a number');
  return args.reduce((acc, n) => acc + n, 0);
};

[...]

  assert({
    given: 'NaN',
    should: 'throw',
    actual: Try(sum, 1, NaN),
    expected: new TypeError('Not a number')
  });
});
```

## 2 - Show examples of how to test an Error

I would add these examples to show how to explicitly test an error's type and its message.

```js
assert({
  given: 'NaN',
  should: 'throw a TypeError',
  actual: Try(sum, 1, NaN) instanceof TypeError,
  expected: true
});

assert({
  given: 'NaN',
  should: 'throw a TypeError with correct message',
  actual: Try(sum, 1, NaN).toString(),
  expected: 'TypeError: NaN'
});

// merged
assert({
  given: 'NaN',
  should: 'throw',
  actual: 
    Try(sum, 1, NaN) instanceof TypeError && 
    Try(sum, 1, NaN).toString() === 'TypeError: NaN',
  expected: true
});
```

Alternatively, one could wrap the `sum` fn call in a try catch and run the assert in the catch itself.

**Comment by ericelliott** [comment]
I'd be willing to accept a PR with this approach:

```js
assert({
  given: 'NaN',
  should: 'throw',
  actual: Try(sum, 1, NaN).toString()
  expected: 'TypeError: NaN'
});
```

**Comment by kyeotic** [comment]
@ericelliott I think the lack of any documentation of the `Try` function is the root cause here. How is the `Try` function intended to be used?

**Comment by ericelliott** [comment]
We have [an open ticket for that](https://github.com/ericelliott/riteway/issues/16). Want to tackle it?
