### ISSUE TITLE
How to run tests without npm

### ISSUE THREAD

**Issue by rhali786** [ericelliott/riteway#109]
Hi, 

I don't have npm installed on staging and prod machines. I'd like to run my tests and am trying to figure out how to do that. 

I suppose I could create a file that searches my *test.js and require them, but this feels a bit heavyhanded. 

Can you help me see how to run my tests in say a lib folder such as helloWorld.test.js without npm?

Thanks!

**Comment by rhali786** [comment]
I may have solved it myself. 

`./node_modules/.bin/riteway 'lib/*/*.test.js' | tap-difflet`

**Comment by ericelliott** [comment]
You would also need to point to the bin for `tap-difflet` inside `./node_modules/.bin/`

**Comment by rhali786** [comment]
Hi @ericelliott , when I try to run this test on my linuxI get this error and I'm not sure how to handle it. 


node_modules/.bin/riteway: line 14: 104923 Segmentation fault      (core dumped) node "$basedir/../riteway/bin/riteway" "$@"
--


Any thoughts?

**Comment by ericelliott** [comment]
I have never seen Node seg fault. JavaScript runs in a sandbox, so the JS code should not cause a segmentation fault. Can you show the exact command you're running?

**Comment by rhali786** [comment]
@ericelliott  the exact line is 


`./node_modules/.bin/riteway 'lib/*/*.test.js'`

Exact Error is 
`./node_modules/.bin/riteway: line 14: 78942 Segmentation fault      (core dumped) node "$basedir/../riteway/bin/riteway" "$@"`

./node_modules/.bin/riteway: line 14: 78942 Segmentation fault      (core dumped) node "$basedir/../riteway/bin/riteway" "$@"
--




./node_modules/.bin/riteway: line 14: 78942 Segmentation fault      (core dumped) node "$basedir/../riteway/bin/riteway" "$@"
--




./node_modules/.bin/riteway: line 14: 78942 Segmentation fault      (core dumped) node "$basedir/../riteway/bin/riteway" "$@"
--




./node_modules/.bin/riteway: line 14: 78942 Segmentation fault      (core dumped) node "$basedir/../riteway/bin/riteway" "$@"
--



--

**Comment by ericelliott** [comment]
Maybe it's core dumping in the fs code that handles the blob? Have you tried running `node lib/somemodule/sometestfile.test.js`? Does that work?
