### ISSUE TITLE
Suggestion of moving render component into its own add on or plug in

### ISSUE THREAD

**Issue by damianof** [ericelliott/riteway#130]
I would keep the library more pure just with the describe/try etc, without the render component that is specific to react, and follow a plugin architecture (or something like that) to add render components for different platforms.

**Comment by ericelliott** [comment]
The render component is already statically separate (not imported or required when you import describe from riteway), but we use it so much with React, it would be inconvenient to move it into another package. Also, React is far and away the leading front end component library, meaning that the majority of RITEWay users are also using React. It makes sense to solve the majority case in the same package, IMO.

We use RITEWay all the time for Node projects which don't use React, and the React render component doesn't bother us at all. Is it causing you any trouble?
