### ISSUE TITLE
testing click

### ISSUE THREAD

**Issue by ischoe** [ericelliott/riteway#131]
I would like to test e.g. when i click the button, is the counter updated. Is this possible? ( I am refering to your clickcounter example)

**Comment by ericelliott** [comment]
Doing so would overlap with and be largely redundant with both your functional tests (for which I recommend [TestCafe](https://devexpress.github.io/testcafe/), and your unit tests for the (hopefully pure) state transformations which actually increment the counter.

Also, if you're essentially mocking out the DOM (e.g., with React's testing tools, Enzyme, etc), you don't actually get good tests of how your UI behaves in real browsers with real DOM APIs. You need to integrate with the real browser APIs for that.

For these reasons, I consider unit tests of UI interactions to be both redundant and invalid. Use functional tests, instead.
