### ISSUE TITLE
How to deal with CSS?

### ISSUE THREAD

**Issue by janhesters** [ericelliott/riteway#149]
I need to test a display component in React which uses CSS.

It imports it like this:

```jsx
import './Cart.css';
```

This throws the error:

```
(function (exports, require, module, __filename, __dirname) { .Cart {
                                                              ^
```

I think this has something to do with Babel or Webpack. At least Jest is solving this by mocking all modules that end with `.css`. How can we solve this with RITEway?

**Comment by ericelliott** [comment]
css imports are not part of the node module or ecmascript module specification, so if you're using this in your project, it's handled via a loader configuration -- probably specified in a [webpack config file](https://webpack.js.org/loaders/css-loader/). Your babel/webpack process for your tests needs to include these kinds of dependencies. This concern is out-of-scope for RITEWay.

**Comment by janhesters** [comment]
For future reference, here is a minimal example repo on how to use RITEway with `.css` and `.module.css` files: https://github.com/janhesters/RITEway-module.css
