### ISSUE TITLE
How to properly assert values are NOT equal?

### ISSUE THREAD

**Issue by 3dos** [ericelliott/riteway#183]
For now, I test values are actually different with a boolean assertion like the following:

```js
assert({
  given: 'something',
  should: 'be different',
  actual: value !== otherValue,
  expected: true
})
```

But I feel this kind of assertion is sketchy and when the test fails, I get a report saying I receive false instead of true without any insight about the actual values.

Do I write this test "correctly"? Is there another way or even shouldn't I have to test for different values?

I ran across this case by testing an array shuffling function. Here I'd like to test the array has actually been shuffled.

**Comment by ericelliott** [comment]
The problem you're encountering is that the function under test is not a pure function.

Is there a pure function you can pass the arrays through that would produce a deterministic result which can provide evidence of correctness?

For a shuffle function:
* call a function that asserts that the arrays are not the same
* call a function that asserts that everything in the first array is also in the second array
* assert on the array length

```js
const arr = [1,2,3];
const arr2 = [2,3,1];

const includesAll = (arr, arr2) => 
  arr.reduce((result, el) => result && arr2.includes(el));

const isArrayDifferent = (arr, arr2) =>
  arr.toString() !== arr2.toString();

console.log(
  includesAll(arr, arr2),
  isArrayDifferent(arr, arr2)
);
```

All you need now are descriptive assertions for them.

```
  assert({
    given: 'an array to shuffle',
    should: 'return an array that contains all the original elements',
    actual: includesAll(arr, arr2),
    expected: true
  });

  assert({
    given: 'an array to shuffle',
    should: 'return an different array',
    actual: isArrayDifferent(arr, arr2),
    expected: true
  });

  assert({
    given: 'an array to shuffle',
    should: 'return a same-sized array',
    actual: arr.length,
    expected: arr2.length
   });
```

**Comment by 3dos** [comment]
Thank you for your help Eric! This is pretty much how I handled the testing. I also wondered about false negatives during testing. I'm using a 52 elements array (a deck of cards) so I think chances are pretty slim for the tests to fail.

So basically when the test fail I'll get a `false => true` report. The test functions `includesAll` and `isArrayDifferent` can output additional insight on the console though.

Thanks again for your time!
