### ISSUE TITLE
Needs to support multiple test files.

### ISSUE THREAD

**Issue by inadarei** [ericelliott/riteway#21]
Current implementation only supports a single test file. In large projects it's typical to organize various tests in multiple file and then indicate a pattern of files in package.json. Typiclaly, you will find an entry such as:

```
"test" :  "test/**/*-test.js",
```

Riteway needs to support the same.

**Comment by ericelliott** [comment]
Thanks! I'll take a look ASAP.

**Comment by inadarei** [comment]
Thank you, Eric. Loved your blog post on RITEway and looking forward to using the approach/module on some of my projects.

**Comment by MartinHelmut** [comment]
Hey, seems like this can be closed based on the merged PR? :)

**Comment by inadarei** [comment]
True :)
