### ISSUE TITLE
Cannot log after tests are done.

### ISSUE THREAD

**Issue by arshmakker** [ericelliott/riteway#236]
Hi,

First of all, thank you for making this library, i was really going to go for jest-cucumber, but then I found your library and felt it was simple, complete and followed the practice of giving a reason for test cases and also the code and hence am trying to get this incorporated in my company.

----------------
My below test, throws an error::
Cannot log after tests are done. Did you forget to wait for something async in your test?

Not sure where to put the 'await' call or do I really need one?

`
import React from 'react';
import { describe } from 'riteway';
import render from 'riteway/render-component';

describe('Hello component', async assert => {

    const $ = render(<div className={'greeting'} >Hello</div>);
    assert({
        given: 'No Params',
        should: 'Render a greeting',
        actual: $('.greeting').length,
        expected: 1
    });
});

`
Regards
Arsh

**Comment by ericelliott** [comment]
Hi Arsh,

> Cannot log after tests are done. Did you forget to wait for something async in your test?

This error message comes from a package upstream from RITEway, and it basically means the tests are never finishing. The message is trying to guess what may have gone wrong, but sometimes the guess is not very helpful.

The problem in this case may be that the environment is not configured correctly? If you can post a GitHub repo demonstrating the error, I'd be willing to take a quick look. I don't have enough information right now to help you.

**Comment by ericelliott** [comment]
Take a look at the React support hints in [the troubleshooting guide](https://github.com/ericelliott/riteway#troubleshooting).

**Comment by arshmakker** [comment]
hi Eric,

Thank you for he direction, I was able to resolve it via .bablerc as stated in the troubleshooting guide, probably we should update the troubleshooting guide with another symptom?

Regards
Arsh
