### ISSUE TITLE
Typescript complains about describe.only and describe.skip

### ISSUE THREAD

**Issue by ericelliott** [ericelliott/riteway#25]

**Comment by johanalkstal** [comment]
I'm using version 6.0.3 and the TS compiler does not recognize the existence of `.only` or `.skip`.
Should they not be a part of the definition file?

**Comment by ericelliott** [comment]
They should, but I haven't had the chance to figure out how to get it working. Open to a PR.

**Comment by ericelliott** [comment]
Looks like this should be fixed in v6.0.3. Can you provide more detail?
