### ISSUE TITLE
TestFunction must return Promise<void>

### ISSUE THREAD

**Issue by Gipphe** [ericelliott/riteway#27]
In `index.d.ts`, `TestFunction` currently has the return type `Promise<void>`, while the docs say the `TestFunction` can return either  `Promise` or `void`. Should the return type instead be `Promise<void> | void`?

In TypeScript, this is an invalid `TestFunction`:

```typescript
describe('foo()', (assert) => {
  assert({
    given: 'some case',
    should: 'return something',
    actual: 'value',
    expected: 'value',
  });
});
```

It *must* return a `Promise<void>`:

```typescript
describe('foo()', (assert) => {
  assert({
    given: 'some case',
    should: 'return something',
    actual: 'value',
    expected: 'value',
  });

  return Promise.resolve();
});
```

or use `async`:

```typescript
describe('foo()', async (assert) => {
  assert({
    given: 'some case',
    should: 'return something',
    actual: 'value',
    expected: 'value',
  });
});
```

**Comment by ericelliott** [comment]
The type in the docs is wrong. The TestFunction should always return a promise. Please feel free to PR the docs.
