### ISSUE TITLE
Type argument for Assertion

### ISSUE THREAD

**Issue by Gipphe** [ericelliott/riteway#28]
Currently, `Assertion`'s type signature is as follows:

```typescript
interface Assertion {
    readonly given: any
    readonly should: string
    readonly actual: any
    readonly expected: any
}
```

given that `actual` and `expected` will never deep equal each other if they are of differing types<sup>[1]</sup>, so the type signature of `Assertion` could be tightened to:

```typescript
interface Assertion<T> {
    readonly given: any
    readonly should: string
    readonly actual: T
    readonly expected: T
}
```

Simplest case of `assert` and `Assertion`, using type arguments:

```typescript
interface Assertion<T> {
  readonly given: any;
  readonly should: string;
  readonly actual: T;
  readonly expected: T;
}

function assert<T>(v: Assertion<T>): void {
  // assert all the things!
}

assert({
  given: 'some condition',
  should: 'return something',
  actual: 'foo',
  expected: 'foo',
});
// passes

assert({
  given: 'some other case',
  should: 'return something else',
  actual: 'bar',
  expected: 'quack',
});
// fails, as you'd expect

assert({
  given: 'a third case',
  should: 'probably return something, but we\'ll never know',
  actual: 'foobar',
  expected: 123,
});
// TSC error: [ts] Type 'number' is not assignable to type 'string'. [2322]
// Type errors are nice.

function fn(v: number): number | string {
  return v % 2 === 0 ? v | String(v);
}
assert({
  given: 'a string case',
  should: 'return a string',
  actual: fn(1),
  expected: '1',
});
assert({
  given: 'a number case',
  should: 'return a number',
  actual: fn(2),
  expected: 2,
});
// both are valid, since `number` and `string` can both be applied to `number | string`.
```

You could even go as far as to make `given` a `T | string` as well, but `given` is only used for describing the test in question, so that would seem somewhat unnecessary and limiting.

Through [type inference](https://www.typescriptlang.org/docs/handbook/type-inference.html), the majority of existing uses of `assert` will not fail.

This is a bit of a personal thought though, as I personally see strict type safety as a valuable tool.

Thoughts?

---

[1]: Well, technically, they can, if we're talking about type aliases or overlapping interfaces, but even TypeScript itself is aware of this, and will allow one type to be applied to another if the first type is a subset of, or identical to, the other type. Example:

```typescript
interface Foo {
  foobar: string;
}

interface Bar {
  foobar: string;
}

const a: Foo = { foobar: 'a' };

function fn(val: Bar): Foo {
  return val;
}

console.log(fn(a));
//=> { foobar: 'a' }
```

**Comment by ericelliott** [comment]
I agree, and I'm open to a PR.
