### ISSUE TITLE
Riteway does not recognise absolute paths to imports

### ISSUE THREAD

**Issue by dshenderson** [ericelliott/riteway#302]
I have the following in my Webpack config:
```
resolve: {
  modules: [
    path.resolve(__dirname, 'src'),
    'node_modules',
    path.resolve('node_modules')
  ]
}
```

However, when I run tests, it doesn't seem to recognise paths pointing to directories in `src`.

For example, if I have
```
import {method_to_test} from 'utils';
```

I get the following error:

> Error: Cannot find module 'utils/method_to_test'

To get it to work, I seem to have to use a relative path:

```
import {method_to_test} from '../../utils';
```

Absolute paths in imported modules are also not properly resolved.

**Comment by dshenderson** [comment]
It's been 3 weeks since I posted this issue. Anyone have any thoughts? I'm trying to avoid relative path hell, but if this isn't resolved I will either have to use relative paths or use a different testing framework, neither of which is ideal. Thanks in advance for any help!

**Comment by ericelliott** [comment]
How are you invoking RITEWay? What does your test script look like? RITEWay doesn't do anything special with respect to module import resolution. You can literally invoke it like `node my/test/folder/file.js` and it will act just like any other JS script you run.

**Comment by dshenderson** [comment]
Thank you, and apologies.

Apologies because you're right, the issue wasn't with RITEWay.

And thank you, because your comment nudged me out of my mental rut.

The tests do not use the Webpack config, but I wan't seeing that. I've resolved the problem by using `babel-plugin-module-resolver`.

Closing the ticket. Thanks!
