### ISSUE TITLE
Cannot find module 'react'

### ISSUE THREAD

**Issue by wzalazar** [ericelliott/riteway#46]
Always is react dependency necessary? 

I started a project from scratch without `React` and Riteway show me this error

`Cannot find module 'react'`

**Comment by ericelliott** [comment]
The temporary workaround is to install React. I'm working on changing the way the `createComponent` API is exported, to separate it from the main export.

**Comment by wzalazar** [comment]
ok, thanks @ericelliott 👍

**Comment by ericelliott** [comment]
Fixed in riteway@6.0.0
