### ISSUE TITLE
RITEway doesn't work out of the box with Create-React-App

### ISSUE THREAD

**Issue by janhesters** [ericelliott/riteway#71]
I'm trying to use RITEway with create-react-app and there seems to be a babel issue.

**Steps to reproduce:**
1. I made a new project.
2. I installed RITEway via `yarn add --dev` and added `"test": "riteway **/*.test.js | tap-color"`, to my package.json. (tap-color is installed globally on my mac.) This replaced the former `"test": "react-scripts test",`.
3. I wrote the tests:

I wanted to write a header using TDD. I wrote a component that should fail all tests:
```js
import React from 'react';

export function Header() {
  return null;
}

export default Header;
```

And wrote the corresponding tests for that:

```js
import React from 'react';
import { describe } from 'riteway';
import render from 'riteway/render-component';

import Header from './';

describe('header', async assert => {
  const $ = render(<Header />);

  assert({
    given: 'just rendering',
    should: "display the string 'rifky'",
    actual: $('header')
      .html()
      .trim(),
    expected: 'rifky'
  });
});
```

But when I run the test via `yarn test` I get the following error:

```bash
(function (exports, require, module, __filename, __dirname) { import React from 'react';
                                                                     ^^^^^

SyntaxError: Unexpected identifier
    at new Script (vm.js:79:7)
    at createScript (vm.js:251:10)
    at Object.runInThisContext (vm.js:303:10)
    at Module._compile (internal/modules/cjs/loader.js:657:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
```

Both my own written test and the default test in `App.test.js` that comes with CRA is failing because of this error.

I guess this has to do with babel. But what am I missing? Why do the RITEway tests not know about `React` or `import`? If this is an issue with my setup, could we add to the `README.md` how to fix this for future readers?

**Comment by ericelliott** [comment]
You'll need to set up the proper Babel transpiling for your particular project. RITEway doesn't know if you're using React, TypeScript or what. Create a .babelrc, then use something like `node -r` to load Babel. You're right that this should be in the docs.

**Comment by ericelliott** [comment]
I've updated the docs.

**Comment by janhesters** [comment]
@ericelliott Thank you very much! 😊

**Comment by magbicaleman** [comment]
Thank you @janhesters for asking this question and @ericelliott for updating the doc. I did run into an "issue" perhaps it's just my ignorance or just being stuck in angularjs for so long, but in the documentation, it explains as follows.

> The problem is likely that you need a `.babeljs` configured with support for esm (standard JavaScript modules) and/or React. If you need React support, that might look something like:

My issue was creating a `.babeljs` file instead of `.babelrc` once I did that, my package.json command worked `"test": "riteway -r @babel/register -r @babel/polyfill 'src/**/*.test.js'",`

**Comment by magbicaleman** [comment]
I also wanted to mimic the behavior of `react-scripts test` in regards to watching and re-running test after using `yarn test`, so I configured my` package.json` this way. This was based on the `package.json` @ericelliott provided in the previous comment.

```
    "test": "watch 'clear && npm run -s rite' src",
    "eject": "react-scripts eject",
    "rite": "riteway -r @babel/register -r @babel/polyfill 'src/**/*.test.js'"
```

**Comment by magbicaleman** [comment]
Finally to add `tap-color`

`yarn add tap-color -D`

Then update my` package.json` script command

```
"rite": "riteway -r @babel/register -r @babel/polyfill 'src/**/*.test.js' | tap-color"
```

Final result: It seems a bit slow, but perhaps optimizing this later somehow, not worried about it right now. 

![2019-08-15 10 52 28](https://user-images.githubusercontent.com/735039/63103317-deebef00-bf4a-11e9-9a9f-91cf2e4815de.gif)

**Comment by ericelliott** [comment]
It's slow because it has to compile the dependencies for JSX -> JS. Not much we can do about that.

**Comment by magbicaleman** [comment]
@ericelliott awesome good to know. I didn't really mess with testing in Jest so I thought by doing what I did I slowed down that process by switching to Rite.
