### ISSUE TITLE
Async tests leaking into others

### ISSUE THREAD

**Issue by dcortes92** [ericelliott/riteway#86]
I believe this is the same issue [reported](https://github.com/substack/tape/issues/364) in tape. 

I have a test that needs to wait for a promise to resolve to do the assertion. As per my understanding, tests run async. That's why the next test doesn't wait for the previous to finish.

All tests pass, however the output is incorrect.

![image](https://user-images.githubusercontent.com/3781536/54883105-66fc1b80-4e27-11e9-86d7-fc9150b9047c.png)

Is there any way to wait for a test to finish?

**Comment by dcortes92** [comment]
I was able to fix this myself. My `H actions` test returns explicitly a promise:

```
import {describe} from riteway;
import {someAsyncAction} from '../some-async-action';

describe('H actions', assert => { // no async here
  return new Promise(resolve => {
     someAsyncAction().then(() => {
         assert({
            ... // your assertions here
         });

         resolve(); // ends the test
     });
  });
})

```

I don't know if this is too hacky (please, let me know if there is a better way to do it). But it worked for me. Now the rest of the tests wait for `H actions` test to finish first to start running.

![image](https://user-images.githubusercontent.com/3781536/54883747-a7ab6300-4e2e-11e9-9011-bcceae74f335.png)

Thanks 🙂

**Comment by ericelliott** [comment]
All tests must return promises in order to behave correctly. This is why we recommend using `async` functions in the readme:

> "The callback function should be an async function so that the test can automatically complete when it reaches the end. RITEWay assumes that all tests are asynchronous. Async functions automatically return a promise in JavaScript, so RITEWay knows when to end each test."
