### ISSUE TITLE
How to select test-id?

### ISSUE THREAD

**Issue by janhesters** [ericelliott/riteway#93]
I want to migrate some of my unit tests from React Testing Library to RITEway.

I'm stuck with a particular one for a list of contacts. Each row in the list of contacts has a `data-testid` attribute like this ``const testId = `contact-${key}`;``. Where key can be `firstName`, `lastName` etc.

```jsx
<div data-testid={testId}>
  {contact[key]}
</div>
```

The tests look like this:

```jsx
describe('ContactList', () => {
  describe('given a list of contacts', () => {
    const props = { contacts };

    it('displays the last name of all contacts', () => {
      const { getAllByTestId } = render(<ContactList {...props} />);

      const given = getAllByTestId('contact-lastName');
      const actual = pluck('textContent')(given);
      const expected = pluck('lastName')(contacts);
      expect(actual).toEqual(expected);
    });
  });
});
```

Where `contacts` is an array of objects (contacts). `pluck` is from `ramda`. As you can see, I already mimicked the `given`, `actual` and `expected` pattern of RITEway.

How can I query for test ids with RITEway? And can you query for multiple like the `getAll` selector?

**Comment by ericelliott** [comment]
> How can I query for test ids with RITEway? And can you query for multiple like the getAll selector?

If you're talking about element ids, there should only be one result in the rendered output. HTML entity IDs should be unique per page.

You can select by id using: `$('anElementID')`

**Comment by ericelliott** [comment]
`$.data('testid')` will return the `testid` value.

`$('div[data-testid="some-id"]'` will select by a specific `testid`.

**Comment by janhesters** [comment]
@ericelliott Thank you for the answer. Interesting, so you think there is no problem with having `className`s scattered over the code to select elements  🤔That would also make working with RITEway and UI libraries like Material-UI easier.

**Comment by ericelliott** [comment]
> you think there is no problem with having classNames scattered over the code to select elements

No problem at all. That's what `className` is for. HTML classes are the selector API of the web.

**Comment by janhesters** [comment]
@ericelliott Thank you for your tips!
